Stop build chain on error - compile renderscript

diff --git a/simulations/dex b/simulations/dex
--- a/simulations/dex
+++ b/simulations/dex
@@ -3,9 +3,23 @@
 javafile=$1
 basename=${javafile:0:-5}
 
+
 classfile="$basename".class
 dexfile="$basename".dex
 
-/usr/bin/javac -source 1.6 -target 1.6 $javafile # dx doesn't support classes compiled with version 1.7
-/opt/android-sdk/build-tools/18.0.1/dx --dex  --output="$dexfile" "$classfile"
-
+# TODO: make the renderscript compile command dynamic
+llvm-rs-cc -emit-bc stupdate.rs -o . -allow-rs-prefix -I/opt/android-sdk/build-tools/18.0.1/renderscript/include/ -I/opt/android-sdk/build-tools/18.0.1/renderscript/clang-include/
+llvm_status=${PIPESTATUS[0]}
+if [ $llvm_status == 0 ];
+then
+    /usr/bin/javac -cp "/opt/android-sdk/platforms/android-18/*:." -source 1.6 -target 1.6 $javafile # dx doesn't support classes compiled with version 1.7
+    javac_status=${PIPESTATUS[0]}
+    if [ $javac_status == 0 ];
+    then
+        /opt/android-sdk/build-tools/18.0.1/dx --dex  --output="$dexfile" "$classfile"
+    else
+        echo "javac failed."
+    fi
+else
+    echo "renderscript compile failed."
+fi
